easy_words = ('ant baboon badger bat bear beaver camel cat clam cobra cougar '
         'coyote crow deer dog donkey duck eagle ferret fox frog goat '
         'goose hawk lion lizard llama mole monkey moose mouse mule newt '
         'otter owl panda parrot pigeon python rabbit ram rat raven '
         'rhino salmon seal shark sheep skunk sloth snake spider '
         'stork swan tiger toad trout turkey turtle weasel whale wolf '
         'wombat zebra ').split()

normal_words = ['abruptly', 'absurd', 'abyss', 'affix', 'askew', 'avenue', 'awkward', 'axiom', 'azure', 'bagpipes', 'bandwagon', 'banjo', 'bayou', 'beekeeper', 'bikini', 'blitz', 'blizzard', 'boggle', 'bookworm', 'boxcar', 'boxful', 'buckaroo', 'buffalo', 'buffoon', 'buxom', 'buzzard', 'buzzing', 'buzzwords', 'caliph', 'cobweb', 'cockiness', 'croquet', 'crypt', 'curacao', 'cycle', 'daiquiri', 'dirndl', 'disavow', 'dizzying', 'duplex', 'dwarves', 'embezzle', 'equip', 'espionage', 'euouae', 'exodus', 'faking', 'fishhook', 'fixable', 'fjord', 'flapjack', 'flopping', 'fluffiness', 'flyby', 'foxglove', 'frazzled', 'frizzled', 'fuchsia', 'funny', 'gabby', 'galaxy', 'galvanize', 'gazebo', 'gizmo', 'glowworm', 'glyph', 'gnarly', 'gnostic', 'gossip', 'grogginess', 'haiku', 'haphazard', 'hyphen', 'iatrogenic', 'icebox', 'injury', 'ivory', 'ivy', 'jackpot', 'jaundice', 'jawbreaker', 'jaywalk', 'jazziest', 'jazzy', 'jelly', 'jigsaw', 'jinx', 'jiujitsu', 'jockey', 'jogging', 'joking', 'jovial', 'joyful', 'juicy', 'jukebox', 'jumbo', 'kayak', 'kazoo', 'keyhole', 'khaki', 'kilobyte', 'kiosk', 'kitsch', 'kiwifruit', 'klutz', 'knapsack', 'larynx', 'lengths', 'lucky', 'luxury', 'lymph', 'marquis', 'matrix', 'megahertz', 'microwave', 'mnemonic', 'mystify', 'naphtha', 'nightclub', 'nowadays', 'numbskull', 'nymph', 'onyx', 'ovary', 'oxidize', 'oxygen', 'pajama', 'peekaboo', 'phlegm', 'pixel', 'pizazz', 'pneumonia', 'polka', 'pshaw', 'psyche', 'puppy', 'puzzling', 'quartz', 'queue', 'quips', 'quixotic', 'quiz', 'quizzes', 'quorum', 'razzmatazz', 'rhubarb', 'rhythm', 'rickshaw', 'schnapps', 'scratch', 'shiv', 'snazzy', 'sphinx', 'spritz', 'squawk', 'staff', 'strength', 'strengths', 'stretch', 'stronghold', 'stymied', 'subway', 'swivel', 'syndrome', 'thriftless', 'thumbscrew', 'topaz', 'transcript', 'transgress', 'transplant', 'triphthong', 'twelfth', 'twelfths', 'unknown', 'unworthy', 'unzip', 'uptown', 'vaporize', 'vixen', 'vodka', 'voodoo', 'vortex', 'voyeurism', 'walkway', 'waltz', 'wave', 'wavy', 'waxy', 'wellspring', 'wheezy', 'whiskey', 'whizzing', 'whomever', 'wimpy', 'witchcraft', 'wizard', 'woozy', 'wristwatch', 'wyvern', 'xylophone', 'yachtsman', 'yippee', 'yoked', 'youthful', 'yummy', 'zephyr', 'zigzag', 'zigzagging', 'zilch', 'zipper', 'zodiac', 'zombie']

hard_words = ['mellifluous', 'serendipitous', 'confound', 'acquiesce', 'acronym', 'ambiguity', 'analogy', 'anachronism', 'andragogy', 'antithesis', 'antonym', 'articulate', 'assonance', 'benchmarking', 'brainstorming', 'circumspect', 'clandestine', 'cognition', 'collaborate', 'colloquial', 'connotation', 'contrived', 'conundrum', 'correlation', 'criterion', 'cumulative', 'curriculum', 'deference', 'developmental', 'dialect', 'diction', 'didactic', 'dissertation', 'divergent', 'egregious', 'eloquence', 'emergent', 'empathy', 'enigma', 'epitome', 'epiphany', 'epitaph', 'erudite', 'existential', 'exponential', 'formative', 'holistic', 'homonym', 'hubris', 'hyperbole', 'incongruous', 'infamy', 'initiation', 'innate', 'intellectual', 'interactive', 'irony', 'jargon', 'juxtaposition', 'malapropism', 'magnanimous', 'mentor', 'metaphor', 'meticulous', 'mnemonic', 'monologue', 'motif', 'myriad', 'nemesis', 'nominal', 'norms', 'obfuscate', 'obtuse', 'onomatopoeia', 'ostentatious', 'oxymoron', 'paradox', 'paraphrase', 'pedantic', 'pedagogy', 'perusal', 'phonemes', 'phonological', 'plagiarism', 'plethora', 'posthumously', 'preposition', 'pretentious', 'pseudonym', 'references', 'reflection', 'rubric', 'sardonic', 'satire', 'simile', 'soliloquy', 'superfluous', 'syntax', 'thesis', 'validity', 'vernacular', 'virtual', 'vocational',]

hard_word_dict = {
'mellifluous': '[adjective] (of a sound) pleasingly smooth and musical to hear.\n',
'serendipitous': '[adjective] occurring or discovered by chance in a happy or beneficial way.\n',
'confound': '[verb] cause surprise or confusion in (someone), especially by not according with their expectations.\n'
}